### ISSUE TITLE
Helou 😎 

### ISSUE THREAD

**Issue by Retr02332** [Ingrid-E/dacris-webapp#1]
¿Estás iniciando un proyecto personal?
¡ Chévere que le estés dando a React !

**Comment by Ingrid-E** [comment]
Es un proyecto de la U, pero se esta tomando 💯 enserio.
React es mi salvador 🤣

**Comment by Retr02332** [comment]
Jajajaja guay !!

Muchos éxitos !!, Igual eres una crack 🙌🏻.

Te hablo al Telegram :)
